"$schema" = "../rule.schema.json"

[[rules]] # Main
regexp = "(.*) '(.*)'"
colors = 'bold red,yellow'

[[rules]] # Directory
regexp = "(.*) (directory) '(.*)'"
colors = 'bold red,bold magenta,yellow'
overwrite = true
